version: '3'
service: 
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image:  chico/nginx
    container_name: nginx
    port:
      - "80:80"
    networks: 
      - production-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongo:
    image: mongo
    networks:
      - production-network

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: chico/alura-books
    container_name: alura-books1
    port:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: chico/alura-books
    container_name: alura-books2
    port:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"
      
  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: chico/alura-books
    container_name: alura-books3
    port:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"
networks:
  production-network:
      driver: bridge
    
